# Generated by Django 4.0.4 on 2022-05-03 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='pst',
            new_name='post',
        ),
    ]
