# Generated by Django 4.0.4 on 2022-05-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postitprofile', '0002_rename_follow_postitprofile_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='postitprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
